# 원핫인코딩 직접구현

In [1]:
# 인코딩 대상 단어를 담은 리스트
word_ls = ['원숭이','바나나','사과','코끼리']

In [15]:
from collections import defaultdict
import numpy as np
# {단어:인덱스} 사전구축
word2id_dic = defaultdict(lambda:len(word2id_dic))

for word in word_ls:
    word2id_dic[word]
    
# 고유단어갯수 : 4개
n_unique_words = len(word2id_dic) 

# 원핫 벡터를 만들기 위해 비어있는 벡터 생성
one_hot_vectors = np.zeros((len(word_ls), n_unique_words))

# 단어고유 인덱스 
for i,word in enumerate(word_ls):
    index = word2id_dic[word]
    one_hot_vectors[i,index] += 1 # 단어 고유 인덱스에 1을 더해줌. 
one_hot_vectors

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# sklearn

In [2]:
# sklearn을 활용한 one-hot encoding
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

# 예제 데이터 배열
values = array(word_ls)

# 문자열에 숫자를 붙임
label_enc = LabelEncoder()
int_enc = label_enc.fit_transform(values)

# binary encode
onehot_enc = OneHotEncoder(sparse=False)
int_enc = int_enc.reshape(len(int_enc), 1) # n:1 matrix로 변환
onehot_enc = onehot_enc.fit_transform(int_enc)
onehot_enc

array([[0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.]])

In [3]:
values

array(['원숭이', '바나나', '사과', '코끼리'], dtype='<U3')

In [4]:
int_enc

array([[2],
       [0],
       [1],
       [3]])