In [ ]:
!pip install '패키지 이름'
conda install '패키지 이름'

Numpy N차원 배열데이터, 행렬계산을 핸들링할 수 있는 패키지

In [2]:
import numpy as np   # 관례적 작성법

In [4]:
np.array([1,2,3])  # 배열객체

array([1, 2, 3])

In [5]:
arr1 = np.array(range(10))
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr2 = np.array([0.1,0.2,0.3])
arr2

array([0.1, 0.2, 0.3])

In [9]:
arr3 = np.array(['a','b','c'])
arr3

array(['a', 'b', 'c'], dtype='<U1')

In [11]:
arr4 = np.array([1,2,'a','b',0.1,0.2])
arr4

array(['1', '2', 'a', 'b', '0.1', '0.2'], dtype='<U11')

In [29]:
arr5 = np.array([1,2,0.3,0.4])
arr5

array([1. , 2. , 0.3, 0.4])

^ 자동으로 모두 실수형으로 변환

In [14]:
arr6 = np.array(
    [[1,2,3],
    [4,5,6],
    [7,8,9]]

)
arr6

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# array의 타입

array는 데이터 타입이 통일되어야 한다.

In [15]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
arr1.dtype # 데이터타입 확인 # 정수형 + 32비트

dtype('int32')

In [19]:
arr2.dtype

dtype('float64')

In [26]:
arr3.dtype  #문자열 #1자리 숫자

dtype('<U1')

In [27]:
print(arr4.dtype) # 문자열.

<U11


In [24]:
print(arr5.dtype)
arr5

float64


array([1. , 2. , 0.2, 0.3])

## shape

In [30]:
arr5

array([1. , 2. , 0.3, 0.4])

In [34]:
arr5.shape   #1차원 데이터에만 #길이가 4인 1차원배열

(4,)

In [35]:
arr6

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
arr6.shape  #행과 열의 길이가 3인 2차원 배열

(3, 3)

## arange, linspace

In [39]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
arr2 = np.arange(3,13)
arr2

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [41]:
arr3 = np.arange(5.0)
arr3

array([0., 1., 2., 3., 4.])

In [42]:
arr4 = np.arange(3,100,3.0)
arr4

array([ 3.,  6.,  9., 12., 15., 18., 21., 24., 27., 30., 33., 36., 39.,
       42., 45., 48., 51., 54., 57., 60., 63., 66., 69., 72., 75., 78.,
       81., 84., 87., 90., 93., 96., 99.])

## linspace

In [44]:
np.linspace(-5, 5, 10)

array([-5.        , -3.88888889, -2.77777778, -1.66666667, -0.55555556,
        0.55555556,  1.66666667,  2.77777778,  3.88888889,  5.        ])

### reshape(배열의 형태 변환)

In [46]:
arr= np.arange(36.0)
arr

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35.])

In [49]:
arr.shape   #1차원

(36,)

In [54]:
arr2 = arr.reshape(12,3)       #1차원 배열을 2차원 배열으로 만들기 (행,열)
arr2


array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.],
       [12., 13., 14.],
       [15., 16., 17.],
       [18., 19., 20.],
       [21., 22., 23.],
       [24., 25., 26.],
       [27., 28., 29.],
       [30., 31., 32.],
       [33., 34., 35.]])

In [55]:
arr2.shape

(12, 3)

In [56]:
arr3 = arr.reshape(3,4,3)
print(arr3.shape)
arr3

(3, 4, 3)


array([[[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]],

       [[12., 13., 14.],
        [15., 16., 17.],
        [18., 19., 20.],
        [21., 22., 23.]],

       [[24., 25., 26.],
        [27., 28., 29.],
        [30., 31., 32.],
        [33., 34., 35.]]])

In [59]:
print(arr1.shape)   # .class  # 바꿀 수 있음
arr1

(10,)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
arr1.shape = (5,2)
arr1

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [65]:
# -1 shape
print(arr3.shape)
arr3

(3, 4, 3)


array([[[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]],

       [[12., 13., 14.],
        [15., 16., 17.],
        [18., 19., 20.],
        [21., 22., 23.]],

       [[24., 25., 26.],
        [27., 28., 29.],
        [30., 31., 32.],
        [33., 34., 35.]]])

In [66]:
arr3.reshape(-1,12)   #데이터 개수가 12의 배수인 것만 알고있을때

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.],
       [12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23.],
       [24., 25., 26., 27., 28., 29., 30., 31., 32., 33., 34., 35.]])

In [67]:
arr3.reshape(-1)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35.])

In [68]:
arr3.reshape(4,-1,3)

array([[[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.]],

       [[ 9., 10., 11.],
        [12., 13., 14.],
        [15., 16., 17.]],

       [[18., 19., 20.],
        [21., 22., 23.],
        [24., 25., 26.]],

       [[27., 28., 29.],
        [30., 31., 32.],
        [33., 34., 35.]]])

### astype  (배열의 데이터타입 dtype 변환)

In [69]:
arr1 = np.arange(5)
arr2 = np.arange(0.0,0.5,0.1)
arr1,arr2

(array([0, 1, 2, 3, 4]), array([0. , 0.1, 0.2, 0.3, 0.4]))

In [70]:
print(arr1.dtype)
print(arr2.dtype)

int32
float64


In [71]:
# int -> float
print(arr1.astype(float))
print(arr1.astype(np.float64))

[0. 1. 2. 3. 4.]
[0. 1. 2. 3. 4.]


In [73]:
# float -> char

print(arr2.astype(str))
print(arr2.astype(np.str))

['0.0' '0.1' '0.2' '0.30000000000000004' '0.4']
['0.0' '0.1' '0.2' '0.30000000000000004' '0.4']


### rand

In [77]:
np.random.rand(5)  #0과1사이의 균일분포 사이

array([0.14795738, 0.2803734 , 0.89959411, 0.45164188, 0.37226238])

In [75]:
np.random.rand(3,3)

array([[0.73630809, 0.29151919, 0.58487741],
       [0.31354482, 0.11358674, 0.89510877],
       [0.7489749 , 0.05191456, 0.66633006]])

In [76]:
np.random.rand(2,2,2)

array([[[0.89851693, 0.80123638],
        [0.99930338, 0.1679426 ]],

       [[0.94858635, 0.47601591],
        [0.69644557, 0.11375212]]])

### randint

In [79]:
np.random.randint(-5,3,(3,3))  #-5부터 3까지 난수를 3,3형태로


array([[-5,  2, -2],
       [-1,  1,  0],
       [ 1, -1, -2]])

### randn

In [80]:
np.random.randn(2,5)

array([[ 0.775545  ,  0.20407339, -0.32693077, -0.98159068, -1.66097938],
       [ 1.63149661, -0.79277905,  0.14739126,  0.58018079, -1.43056495]])

## array의 indexing, slicing

nd_array[start:stop:step, start:stop:step]

nd_array[seq_data<[indexing1, indexing2]>]


In [84]:
arr1 = np.arange(0,100,10.0)
arr1

array([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])

In [86]:
arr1[0],arr1[-1]

(0.0, 90.0)

In [87]:
arr1[:],arr1[4:],arr1[1:8]

(array([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.]),
 array([40., 50., 60., 70., 80., 90.]),
 array([10., 20., 30., 40., 50., 60., 70.]))

In [89]:
arr1[::2] # 2칸씩 이동

array([ 0., 20., 40., 60., 80.])

#### n-Dim Array Indecing, Slicing

In [92]:
# 2차원 배열 : 0~23까지 (8,3)의 배열을 만드세요

arr2 = np.arange(24.0).reshape(8,3)
arr2

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.],
       [12., 13., 14.],
       [15., 16., 17.],
       [18., 19., 20.],
       [21., 22., 23.]])

In [94]:
arr2[0],arr2[4]   #행 추출

(array([0., 1., 2.]), array([12., 13., 14.]))

In [100]:
print(arr2[3][1])   #연산을 두번해서 성능이 느림
    

10.0


다차원 배열 인덱싱

In [99]:
# 일반적
print(arr2[3,1]) 

10.0


다차원 배열 슬라이싱

In [103]:
# 3행의 1부터
print(arr2[3,1:])  

[10. 11.]


In [102]:
#3행부터 1열부터
print(arr2[3:,1:])   

[[10. 11.]
 [13. 14.]
 [16. 17.]
 [19. 20.]
 [22. 23.]]


In [104]:
#전체, step이 2, 전체출력
print(arr2[::2,:])    

[[ 0.  1.  2.]
 [ 6.  7.  8.]
 [12. 13. 14.]
 [18. 19. 20.]]


In [106]:
arr2

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.],
       [12., 13., 14.],
       [15., 16., 17.],
       [18., 19., 20.],
       [21., 22., 23.]])

In [112]:
print(arr2[[0,5,3]])

print('-'*10)

print(arr2[[0,5,3],[1]])

print('-'*10)

print(arr2[
    [0,5,3], [1]
])

[[ 0.  1.  2.]
 [15. 16. 17.]
 [ 9. 10. 11.]]
----------
[ 1. 16. 10.]
----------
[ 1. 16. 10.]


#### 조건으로 배열 indexing

In [114]:
arr2>10

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [113]:
# 2차원 배열이 인덱싱에 들어가면 True만 출력됨

arr2[arr2>10]   

array([11., 12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23.])

In [115]:
# 홀수

arr2[arr2%2==1]   

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19., 21., 23.])

### numpy의 상수  NaN Inf

In [120]:
arr = np.array([1,2,3,np.nan,np.inf,-np.inf])
print('dtype:',arr.dtype)
arr

dtype: float64


array([  1.,   2.,   3.,  nan,  inf, -inf])

## 배열의 연산

In [121]:
arr1 = np.arange(0,10,1)
arr2 = np.arange(1,0,-0.1)
arr1,arr2

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([1. , 0.9, 0.8, 0.7, 0.6, 0.5, 0.4, 0.3, 0.2, 0.1]))

In [122]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [127]:
# array 와 scalar 연산
#broadcasting
arr1 + 1,arr1 + [1,1,1,1,1,1,1,1,1,1]

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]))

In [128]:
# 배열연산

print(arr1-1)
print(arr1*10)
print(arr1/10)
print(arr1**2)
print(arr1%2)

[-1  0  1  2  3  4  5  6  7  8]
[ 0 10 20 30 40 50 60 70 80 90]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
[ 0  1  4  9 16 25 36 49 64 81]
[0 1 0 1 0 1 0 1 0 1]


In [129]:
arr1, arr2

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([1. , 0.9, 0.8, 0.7, 0.6, 0.5, 0.4, 0.3, 0.2, 0.1]))

In [130]:
#요소별 연산
#벡터 연산에서는 요소별 연산 가능

arr1 + arr2

array([1. , 1.9, 2.8, 3.7, 4.6, 5.5, 6.4, 7.3, 8.2, 9.1])

In [132]:

print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)
print(arr1 ** arr2)
print(arr1 % arr2)


[-1.   0.1  1.2  2.3  3.4  4.5  5.6  6.7  7.8  8.9]
[0.  0.9 1.6 2.1 2.4 2.5 2.4 2.1 1.6 0.9]
[ 0.          1.11111111  2.5         4.28571429  6.66666667 10.
 15.         23.33333333 40.         90.        ]
[0.         1.         1.74110113 2.15766928 2.29739671 2.23606798
 2.04767251 1.79278996 1.51571657 1.24573094]
[0.  0.1 0.4 0.2 0.4 0.5 0.4 0.1 0.2 0.1]


In [133]:
arr1 > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [134]:
arr1 > arr2

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

## 행렬

In [136]:
# 0행렬
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [137]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### 일행렬

In [138]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [139]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

#### 단위행렬

In [141]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [143]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [144]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [145]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## 통계를 위한 연산

In [147]:
arr1 = np.arange(1,11.0).reshape(5,2)
arr1

array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.],
       [ 7.,  8.],
       [ 9., 10.]])

### sum

In [148]:
arr1.sum()

55.0

In [149]:
# 행단위로 연산
# axis = 0 바깥쪽 
# 컬럼별
arr1.sum(axis=0)

array([25., 30.])

In [151]:
arr1.sum(axis=1)

array([ 3.,  7., 11., 15., 19.])

### mean

In [153]:
arr1.mean()

5.5

In [154]:
arr1.mean(axis=0)

array([5., 6.])

In [155]:
arr1.mean(axis=1)

array([1.5, 3.5, 5.5, 7.5, 9.5])

### var

In [157]:
arr1.var()

8.25

In [158]:
arr1.var(axis=1)

array([0.25, 0.25, 0.25, 0.25, 0.25])

### std

In [159]:
arr1.std()

2.8722813232690143

In [162]:
arr1.std(axis=0)

array([2.82842712, 2.82842712])

In [163]:
arr1.std(axis=1)

array([0.5, 0.5, 0.5, 0.5, 0.5])

### min

In [175]:
print(arr1.min())
print(arr1.min(axis=0))
print(arr1.min(axis=1))

1.0
[1. 2.]
[1. 3. 5. 7. 9.]


### max

In [176]:
print(arr1.max())
print(arr1.max(axis=0))
print(arr1.max(axis=1))

10.0
[ 9. 10.]
[ 2.  4.  6.  8. 10.]


### nd_arr.cumsum() - 누적합

In [177]:
arr1

array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.],
       [ 7.,  8.],
       [ 9., 10.]])

In [179]:
arr1.cumsum()

array([ 1.,  3.,  6., 10., 15., 21., 28., 36., 45., 55.])

In [180]:
arr1.cumsum(axis=0)

array([[ 1.,  2.],
       [ 4.,  6.],
       [ 9., 12.],
       [16., 20.],
       [25., 30.]])

In [181]:
arr1.cumsum(axis=1)

array([[ 1.,  3.],
       [ 3.,  7.],
       [ 5., 11.],
       [ 7., 15.],
       [ 9., 19.]])

### nd_arr.cumprod() - 누적곱

In [182]:
arr1.cumprod()

array([1.0000e+00, 2.0000e+00, 6.0000e+00, 2.4000e+01, 1.2000e+02,
       7.2000e+02, 5.0400e+03, 4.0320e+04, 3.6288e+05, 3.6288e+06])

In [183]:
arr1.cumprod(axis=0)

array([[1.00e+00, 2.00e+00],
       [3.00e+00, 8.00e+00],
       [1.50e+01, 4.80e+01],
       [1.05e+02, 3.84e+02],
       [9.45e+02, 3.84e+03]])

In [184]:
arr1.cumprod(axis=1)

array([[ 1.,  2.],
       [ 3., 12.],
       [ 5., 30.],
       [ 7., 56.],
       [ 9., 90.]])

### sqrt, log, exp

In [186]:
#양의제곱근
np.sqrt(arr1.var(axis=1))

array([0.5, 0.5, 0.5, 0.5, 0.5])

In [169]:
# 로그
np.log(arr1)

array([[0.        , 0.69314718],
       [1.09861229, 1.38629436],
       [1.60943791, 1.79175947],
       [1.94591015, 2.07944154],
       [2.19722458, 2.30258509]])

In [168]:
# 지수
np.exp(arr1)

array([[2.71828183e+00, 7.38905610e+00],
       [2.00855369e+01, 5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03],
       [8.10308393e+03, 2.20264658e+04]])

In [170]:
2.5e+3

2500.0

In [171]:
2.5e-2

0.025

## 행렬연산

In [188]:
arr1 = np.arange(1,7).astype(np.float64).reshape(2,3)
arr2 = np.arange(6,0,-1.0).astype(np.float64).reshape(3,2)
arr1, arr2

(array([[1., 2., 3.],
        [4., 5., 6.]]),
 array([[6., 5.],
        [4., 3.],
        [2., 1.]]))

In [189]:
arr1.shape,arr2.shape

((2, 3), (3, 2))

### 행렬곱

In [191]:
arr1 @ arr2

array([[20., 14.],
       [56., 41.]])

In [193]:
# 일반적
arr1.dot(arr2)

array([[20., 14.],
       [56., 41.]])

In [194]:
np.matmul(arr1,arr2)

array([[20., 14.],
       [56., 41.]])

### 전치

In [201]:
arr1

array([[1., 2., 3.],
       [4., 5., 6.]])

In [202]:
arr3 = np.arange(6).reshape(2,3)
arr3

array([[0, 1, 2],
       [3, 4, 5]])

In [204]:
#행렬곱 불가
arr1.shape, arr3.shape

((2, 3), (2, 3))

In [205]:
arr3.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [207]:
arr3.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [208]:
arr1.dot(arr3.T)

array([[ 8., 26.],
       [17., 62.]])

### 역행렬
np.linalg.inv(A)

In [210]:
arr1 = np.arange(1,5).reshape(2,2)
arr1

array([[1, 2],
       [3, 4]])

In [212]:
arr2 = np.linalg.inv(arr1)
arr2

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [214]:
arr1.dot(arr2)

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

In [217]:
arr2.dot(arr1)  #단위행렬 출력

array([[1.0000000e+00, 4.4408921e-16],
       [0.0000000e+00, 1.0000000e+00]])

1.11022302e-16, 4.4408921e-16 처럼 작은 수는 0으로 본다.

## concat
행렬 2개 연결

np.concatenate((a1, a2, ...), axis=0, out=None)

In [218]:
arr1 = np.arange(4).reshape(2,2)
arr2 = np.arange(0,40,10).reshape(2,2)
arr1, arr2

(array([[0, 1],
        [2, 3]]),
 array([[ 0, 10],
        [20, 30]]))

In [223]:
np.concatenate((arr1,arr2), axis=0)   # axis=0 이 default

array([[ 0,  1],
       [ 2,  3],
       [ 0, 10],
       [20, 30]])

In [224]:
np.concatenate((arr1,arr2), axis=1)

array([[ 0,  1,  0, 10],
       [ 2,  3, 20, 30]])

In [225]:
# np.c_

np.c_[arr1,arr2]


array([[ 0,  1,  0, 10],
       [ 2,  3, 20, 30]])

# 연습문제

In [289]:
# 1

arr1 = np.zeros(10)
arr1[[4,5]] = 1
# arr1[4:6] = 1
print(arr1.reshape(5,2))

[[0. 0.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [0. 0.]]


In [243]:
# 2

arr2 = np.arange(10,30,2)
arr2
a = np.arange(1,2,0.1)
a

print(arr2 + a)
print(arr2 - a)
print(arr2 * a)
print(arr2 / a)
print(arr2 ** a)
print(arr2 % a)


[11.  13.1 15.2 17.3 19.4 21.5 23.6 25.7 27.8 29.9]
[ 9.  10.9 12.8 14.7 16.6 18.5 20.4 22.3 24.2 26.1]
[10.  13.2 16.8 20.8 25.2 30.  35.2 40.8 46.8 53.2]
[10.         10.90909091 11.66666667 12.30769231 12.85714286 13.33333333
 13.75       14.11764706 14.44444444 14.73684211]
[ 10.          15.38506625  23.73305484  36.75834736  57.19808742
  89.4427191  140.56470624 222.00313682 352.3319491  561.8239639 ]
[0.  1.  0.8 0.4 1.2 0.5 1.2 0.2 0.8 1.4]


In [292]:
# 3

#arr3 = np.arange(1,101).reshape(-1,10)
arr3 = np.linspace(1,100,10)
arr3

print(arr3.sum())

print(arr3.mean())

print(arr3.std())

print(arr3.var())

print(arr3.min())

print(arr3.max())

print(arr3.cumsum())

print(arr3.cumprod())


505.0
50.5
31.595094555959157
998.25
1.0
100.0
[  1.  13.  36.  70. 115. 171. 238. 316. 405. 505.]
[1.00000000e+00 1.20000000e+01 2.76000000e+02 9.38400000e+03
 4.22280000e+05 2.36476800e+07 1.58439456e+09 1.23582776e+11
 1.09988670e+13 1.09988670e+15]


In [262]:
# 4

arr4 = np.random.randint(0.0,10.0,(3,3)).astype(np.float64)
arr4

array([[8., 8., 9.],
       [2., 7., 7.],
       [7., 2., 0.]])

In [299]:
# 4
arr4 = np.random.rand(3,3)
arr4 = arr4 * 10
arr4

array([[7.08072578, 0.20584494, 9.69909852],
       [8.32442641, 2.12339111, 1.81824967],
       [1.8340451 , 3.04242243, 5.24756432]])

In [298]:
# 랜덤값 저장
# 42번째 랜덤값만 
np.random.seed(42)
arr4 = np.random.rand(3,3)
arr4 = arr4 * 10
arr4

array([[3.74540119, 9.50714306, 7.31993942],
       [5.98658484, 1.5601864 , 1.5599452 ],
       [0.58083612, 8.66176146, 6.01115012]])

In [264]:
# 5

arr5 = np.random.randint(0.0,10.0,(3,3))
arr5

arr5.dtype

dtype('int32')

In [288]:
# 6

arr6= np.arange(1,11).reshape(5,2)
arr_mean = arr6.mean(axis=0)
arr_std = arr6.std(axis=0)


st = (arr6 - arr_mean)/(arr_std)
st

array([[-1.41421356, -1.41421356],
       [-0.70710678, -0.70710678],
       [ 0.        ,  0.        ],
       [ 0.70710678,  0.70710678],
       [ 1.41421356,  1.41421356]])

In [285]:
# 7

arr6
arr_min = arr6.min()
arr_max = arr6.max()

min_max = (arr6 - arr_min)/(arr_max-arr_min)
min_max

array([[0.        , 0.11111111],
       [0.22222222, 0.33333333],
       [0.44444444, 0.55555556],
       [0.66666667, 0.77777778],
       [0.88888889, 1.        ]])

# ------------------------------------------------------------

### 분포도 차이 맞추기

In [302]:
#6 

arr1 = np.linspace(-1000,1000,5)
arr2 = np.linspace(0,10,5)

arr1 = arr1.reshape(5,-1)
arr2 = arr2.reshape(5,-1)
arr3 = np.concatenate((arr1,arr2),axis= 1)

arr3


array([[-1000. ,     0. ],
       [ -500. ,     2.5],
       [    0. ,     5. ],
       [  500. ,     7.5],
       [ 1000. ,    10. ]])

In [303]:
arr1.std(), arr2.std()

(707.1067811865476, 3.5355339059327378)

평균을 기점으로 거리를 봄

In [310]:
arr4 = (arr3 - arr3.mean(axis=0))/arr3.std(axis=0)
print(arr4)

[[-1.41421356 -1.41421356]
 [-0.70710678 -0.70710678]
 [ 0.          0.        ]
 [ 0.70710678  0.70710678]
 [ 1.41421356  1.41421356]]


In [309]:
# 표준화
arr4.mean(), arr4.std(), arr4.var()

(0.0, 0.9999999999999999, 0.9999999999999998)