In [1]:
import numpy as np

In [3]:
ar = np.array([0,1,2,3,4,5,6,7,8,9])
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
type(ar)

numpy.ndarray

-  파이썬은 연속적인 메모리 배치가 불가
-  numpy를 사용
-  벡터화연산을 지원

## 2차원 배열 만들기

In [7]:
c = np.array([[0,1,2],[3,4,5]]) # 2 x 3 arrary
c

array([[0, 1, 2],
       [3, 4, 5]])

In [9]:
# 행의개수
len(c)

2

In [11]:
# 열의 개수
len(c[0])

3

In [14]:
d = np.array([[10,20,30,40],
              [50,60,70,80]])
d

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

## 3차원 배열 만들기
array의 shape를 아는 것이 가장 중요

-  2 x 3 x 4
-  3 x 4 배열의 행렬이 2개

In [17]:
a = np.array([1,2,3])
print(a.ndim)  #1차원
print(a.shape)

1
(3,)


##  다차원 배열의 인덱싱

In [20]:
d[0,0]  #첫번째 행의 첫번째 열

10

In [19]:
d[-1,-1] # 마지막 행의 마지막 열

80

## 슬라이싱

In [22]:
a = np.array([[0,1,2,3],
             [4,5,6,7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [27]:
a[0,:] # 전체 열중에서 1행 출력

array([0, 1, 2, 3])

In [26]:
a[:,1] #전체 행 중에서 2열 출력

array([1, 5])

In [28]:
a[1,1:] # 두번째 행에서 두번째열부터 끝까지 출력

array([5, 6, 7])

### 연습문제

In [30]:
m = np.array([[0,1,2,3,4],
             [5,6,7,8,9],
             [10,11,12,13,14]])
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [34]:
m[1,2]

7

In [35]:
m[2,-1]

14

In [37]:
m[1,1:3]

array([6, 7])

In [46]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [47]:
a[a % 3 ==0]

array([ 3,  6,  9, 12, 15, 18])

In [48]:
a[a % 4 ==1]

array([ 1,  5,  9, 13, 17])

In [50]:
a[(a % 3) + ((a - 1) % 4) == 0]

array([9])

In [52]:
a = np.arange(1,21,dtype='f')
a.dtype

dtype('float32')

In [62]:
a = np.arange(1,21,dtype='U')
a.dtype

ValueError: no fill-function for data-type.

 type이 안맞는 것끼리 연산을 하면 type error

### Inf와 Nan

In [ ]:
# 요소끼리 나누기

np.array([0,1,-1,0])/

In [54]:
np.log(0)

C:\ProgramData\Anaconda3\envs\test_envs\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


-inf

In [61]:
np.log(10)

2.302585092994046

In [58]:
np.exp(-np.inf)  #???????? nummpy에서는 inf가 하나의 숫자처럼 인식? 무한대니까 0

0.0

In [64]:
c = np.zeros((5,2),dtype='i')
c

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [66]:
d = np.zeros(5,dtype='U4')
d   
#null값 들어가는걸로 활용할때


array(['', '', '', '', ''], dtype='<U4')

In [67]:
e = np.ones((2,3,4),dtype='i8')
e

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int64)

크기를 튜플로 명시하지 않고 다른 배열과 같은 크기의 배열을 생성하고 싶다면
zeros_like ones_like

배열하나에 많은 데이터가 들어가면, 초기화를 시킬때 resource가 많이 필요함
resource를 절약하기 위해서 -> empty


In [69]:
g = np.empty((4,3))
g

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [71]:
np.arange(10,20,2)  #19까지

array([10, 12, 14, 16, 18])

-  linspace
-  logspace

In [74]:
np.linspace(0,100,11)   # 0부터 100까지 (100포함) 5개로 나눔 동일한 간격으로

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [76]:
np.logspace(0.1,1,10)   #10의 0.1승과 10의 1승의 사이를 n개(=10)의 점으로 나누어서 생성한다.

array([ 1.25892541,  1.58489319,  1.99526231,  2.51188643,  3.16227766,
        3.98107171,  5.01187234,  6.30957344,  7.94328235, 10.        ])

In [77]:
A = np.array([[1,2,3],[4,5,6]])

In [78]:
# 2 X 3
A

array([[1, 2, 3],
       [4, 5, 6]])

In [80]:
# 전치행렬 3 x 2
A.T  

array([[1, 4],
       [2, 5],
       [3, 6]])

### reshape

In [82]:
a= np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [83]:
b=  a.reshape(3,4)

In [84]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [85]:
a.reshape(3,-1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [86]:
a.reshape(2,2,-1)  # 차원,행,열

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [87]:
a.reshape(2,-1,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

flatten = ravel

In [88]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [91]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [94]:
x = np.arange(5)
x   #벡터

array([0, 1, 2, 3, 4])

In [97]:
x = x.reshape(1,5)
x    # 1행만 있는 행렬

array([[0, 1, 2, 3, 4]])

np.newaxis = 같은 배열에 대해 차원만 증가시키는 

np.hstack
가로로 쌓기

np.vstack 세로로 쌓기

np.dstack([a1,a2])  똑같은 shpae의 행렬을 짝을 지은 것으로 새로 만듦

In [99]:
a = np.array([[0,1,2],
             [3,4,5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [100]:
np.tile(a,2)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [102]:
# ??????????????
np.tile(a,(3,2))

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [103]:
x = np.arange(3)

In [104]:
y = np.arange(5)

In [ ]:
x,y = np.mashgrid???

### 벡터화 연산

In [105]:
x = np.arange(1,1001)
y = np.arange(1001,2001)

In [107]:
%%time 
#시간이 얼마나 걸리니??
z = np.zeros_like(x)
for i in range(1000):
    z[i] = x[i]+y[i]

Wall time: 997 µs


In [108]:
z

array([1002, 1004, 1006, 1008, 1010, 1012, 1014, 1016, 1018, 1020, 1022,
       1024, 1026, 1028, 1030, 1032, 1034, 1036, 1038, 1040, 1042, 1044,
       1046, 1048, 1050, 1052, 1054, 1056, 1058, 1060, 1062, 1064, 1066,
       1068, 1070, 1072, 1074, 1076, 1078, 1080, 1082, 1084, 1086, 1088,
       1090, 1092, 1094, 1096, 1098, 1100, 1102, 1104, 1106, 1108, 1110,
       1112, 1114, 1116, 1118, 1120, 1122, 1124, 1126, 1128, 1130, 1132,
       1134, 1136, 1138, 1140, 1142, 1144, 1146, 1148, 1150, 1152, 1154,
       1156, 1158, 1160, 1162, 1164, 1166, 1168, 1170, 1172, 1174, 1176,
       1178, 1180, 1182, 1184, 1186, 1188, 1190, 1192, 1194, 1196, 1198,
       1200, 1202, 1204, 1206, 1208, 1210, 1212, 1214, 1216, 1218, 1220,
       1222, 1224, 1226, 1228, 1230, 1232, 1234, 1236, 1238, 1240, 1242,
       1244, 1246, 1248, 1250, 1252, 1254, 1256, 1258, 1260, 1262, 1264,
       1266, 1268, 1270, 1272, 1274, 1276, 1278, 1280, 1282, 1284, 1286,
       1288, 1290, 1292, 1294, 1296, 1298, 1300, 13

In [109]:
%%time
z = x+y

Wall time: 0 ns


In [110]:
z

array([1002, 1004, 1006, 1008, 1010, 1012, 1014, 1016, 1018, 1020, 1022,
       1024, 1026, 1028, 1030, 1032, 1034, 1036, 1038, 1040, 1042, 1044,
       1046, 1048, 1050, 1052, 1054, 1056, 1058, 1060, 1062, 1064, 1066,
       1068, 1070, 1072, 1074, 1076, 1078, 1080, 1082, 1084, 1086, 1088,
       1090, 1092, 1094, 1096, 1098, 1100, 1102, 1104, 1106, 1108, 1110,
       1112, 1114, 1116, 1118, 1120, 1122, 1124, 1126, 1128, 1130, 1132,
       1134, 1136, 1138, 1140, 1142, 1144, 1146, 1148, 1150, 1152, 1154,
       1156, 1158, 1160, 1162, 1164, 1166, 1168, 1170, 1172, 1174, 1176,
       1178, 1180, 1182, 1184, 1186, 1188, 1190, 1192, 1194, 1196, 1198,
       1200, 1202, 1204, 1206, 1208, 1210, 1212, 1214, 1216, 1218, 1220,
       1222, 1224, 1226, 1228, 1230, 1232, 1234, 1236, 1238, 1240, 1242,
       1244, 1246, 1248, 1250, 1252, 1254, 1256, 1258, 1260, 1262, 1264,
       1266, 1268, 1270, 1272, 1274, 1276, 1278, 1280, 1282, 1284, 1286,
       1288, 1290, 1292, 1294, 1296, 1298, 1300, 13

### 브로드캐스팅


### 행렬곱(Numpy dot)

In [111]:
x = np.array([[1,2,3],
            [4,5,6]])
y = np.array([[10,100,1000],
            [10000,100000,1000000]])

In [114]:
z = x * y
z
# 행렬곱이 아닌 각 자리에 위치한 것끼리 곱해짐

array([[     10,     200,    3000],
       [  40000,  500000, 6000000]])

In [118]:
# 행렬곱을 하고 싶으면 Numpy.dot
np.dot(x,y.T)
# == np.matmul 

array([[   3210, 3210000],
       [   6540, 6540000]])

In [117]:
x.dot(y.T)

array([[   3210, 3210000],
       [   6540, 6540000]])

In [ ]:
# 행렬곱의 차원을 맞추는 것이 중요하다.

In [119]:
np.sum(x)

21

In [120]:
x.sum()

21

In [122]:
x.min()

1

최소값의 위치

In [123]:
x.argmin()

0

In [124]:
x.mean()

3.5

In [125]:
np.mean(x)

3.5

In [126]:
np.median(x)

3.5

-  np.sort(x)
-  axis= -1과 axis=1과 동일하다 
-  axis = 1이면 행방향 정렬
-  axis = 0이면 열방향 정렬
- sort는 본 객체까지 바꿔버림
-  argsort는 자기자신이 안바뀜. 인덱스를 sort??? 인덱스를 return하니까

### csv파일 읽기

파일 위치 지정안하면 c드라이브 user

In [ ]:
a = np.loadtxt('       .csv',delicator= ',')  #불러오기

In [ ]:
np.savetxt('위치~~~/x1.txt'x1)    #저장