In [1]:
import numpy as np

In [ ]:
np.mean(x)
np.var(x)  # 분산
np.var(x,ddof = 1)  # 비편향 분산  # n-1로 나누는 경우, 

In [ ]:
np.std(x) # 표준편차
np.sqrt(np.var(x))  # 분산의 제곱근 = 표준편차

In [ ]:
np.max(x)
np.min(x)
np.median(x)

# 사분위수

np.percentile(x,0) # 최소값
np.percentil(x,25)  # 1사분위수


sciPy 패키지에는 여러가지 기술 통계값을 한번에 구해주는 describe명령이 있음

In [ ]:
from scipy.stats import describe

### 난수 발생과 카운팅

### 시드 

In [5]:
np.random.seed(0)

In [6]:
np.random.rand(5)  # 숫자는 발생 개수, # rand명령은 0과 1사이의 난수를 발생 # np.array형태로

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [8]:
np.random.seed(0)

In [10]:
np.random.rand(5)   #seed값이 같기 때문에 같은 값이 나옴

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152])

In [12]:
# python의 range 같은 개념 
# = np.range(0,10,1)

x = np.arange(10) 

In [15]:
np.random.shuffle(x)
x

array([8, 6, 4, 9, 2, 0, 5, 1, 7, 3])

### 데이터 샘플링

In [16]:
np.random.choice(5, 5, replace = False)  # shuffle 명령과 같음 # 0부터 4까지의 숫자 5개 출력 
# replace False라는 것은 같은 값 중복 없음
# rsplace True라는 것은 같은 값 중복 있음

array([1, 4, 2, 3, 0])

In [19]:
# 선택확률을 다르게 지정
np.random.choice(5,10, p=[0.1,0,0.3,0.6,0])

array([3, 2, 3, 2, 2, 2, 2, 2, 2, 3])

In [20]:
np.random.rand(10)

array([0.44994999, 0.61306346, 0.90234858, 0.09928035, 0.96980907,
       0.65314004, 0.17090959, 0.35815217, 0.75068614, 0.60783067])

In [22]:
np.random.rand(3,5)   # 3.5 shape를 가진 2차원 배열로 데이터를 만듦

array([[0.94957105, 0.66252687, 0.01357164, 0.6228461 , 0.67365963],
       [0.971945  , 0.87819347, 0.50962438, 0.05571469, 0.45115921],
       [0.01998767, 0.44171092, 0.97958673, 0.35944446, 0.48089353]])

In [23]:
np.random.rand(3,5,2) # 3차원, 5.2 행렬

array([[[0.68866118, 0.88047589],
        [0.91823547, 0.21682214],
        [0.56518887, 0.86510256],
        [0.50896896, 0.91672295],
        [0.92115761, 0.08311249]],

       [[0.27771856, 0.0093567 ],
        [0.84234208, 0.64717414],
        [0.84138612, 0.26473016],
        [0.39782075, 0.55282148],
        [0.16494046, 0.36980809]],

       [[0.14644176, 0.56961841],
        [0.70373728, 0.28847644],
        [0.43328806, 0.75610669],
        [0.39609828, 0.89603839],
        [0.63892108, 0.89155444]]])

In [ ]:
np.random.randn(3,5)  #  표준정규분포 (3x5)의 난수 발생

### 평균이 mu이고 표준편차가 sigma인 정규분포에서 난수 발생

In [24]:
sigma, mu = 1.5, 2.0

c = sigma * np.random.randn(10) + mu
print(c)

[ 1.19229776  4.86269315  1.286336    4.16109668  0.27638648  3.20857183
  4.63416055  3.45946987 -0.32667867  2.28671522]


### 정수 난수발생

0부터 9까지의 숫자 20개 출력

In [25]:
np.random.randint(10, size = 20) 

array([8, 0, 4, 9, 6, 5, 7, 8, 8, 9, 2, 8, 6, 6, 9, 1, 6, 8, 8, 3])

In [34]:
##### 10에서 19까지 중에서 size 갯수 만큼 출력
np.random.randint(10,20, size = 10)

array([15, 13, 13, 17, 19, 19, 19, 17, 13, 12])

### 정수 데이터 카운팅

In [28]:
np.unique([11,11,2,2,34,34])

array([ 2, 11, 34])

In [30]:
a = np.array(['a','b','b','c','a'])
index, count = np.unique(a, return_counts = True)

In [31]:
index

array(['a', 'b', 'c'], dtype='<U1')

In [32]:
count

array([2, 2, 1], dtype=int64)

In [33]:
### 0이 6개 들어있는 빈방 6개를 만들고 인덱스가 값인 자리에 갯수를 카운트해서 출력
np.bincount([1,1,2,2,2,3], minlength = 6)

array([0, 2, 3, 1, 0, 0], dtype=int64)